# Generated by Django 5.0.7 on 2024-08-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
    ]
