# Generated by Django 5.0.7 on 2024-08-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0002_remove_job_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('number_of_employees', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='jobs_api.company'),
        ),
    ]
