# Generated by Django 5.0.7 on 2024-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0004_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='company_pics'),
        ),
    ]
