name: JobsAPI CI/CD Pipeline

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10
        ports:
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
  
    - name: Build Docker images
      run: |
        docker compose build

    - name: Start services
      run: |
        docker compose up -d

    - name: Wait for Postgres to be ready
      run: |
        ./wait-for-it.sh postgres:5432 -- echo "Postgres is up"

    - name: Run migrations
      run: |
        docker compose run --rm django python manage.py migrate



    - name: Stop and remove services
      if: always()
      run: |
        docker compose down

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
